# module
import pandas as pd


class excel_controller:

    def __init__(self):
        self.data = ''
        self.data_value = []
        self.data_header = []

    # excel 읽어오기
    def call_excel(self, file_route):

        self.data = pd.read_excel(file_route)
        # if "signal peptide == NaN" or "Sequence == NaN", remove
        self.data[['Signal peptide', 'Sequence']].dropna()
        self.data_value = self.data.values.tolist()
        self.data_header = self.data.columns.tolist()
        return self.data_value, self.data_header


class seq_controller:

    def __init__(self):
        self.end_number = ''
        self.start_number = ''
        self.seq = ''
        self.signal_peptide = ''
        self.new_seq = []

    # Signal peptide 첫 번호, 끝 번호 찾기
    def string_control(self, fulltext):
        self.end_number = fulltext[fulltext.find('..')+2:fulltext.find(';')]
        self.start_number = fulltext[fulltext.find('SIGNAL')+len('SIGNAL'):fulltext.find('..')]
        return int(self.start_number), int(self.end_number)

    # Sequence 자르기
    def sequence_slice(self, sequence, signal_text):
        start_num, end_num = self.string_control(signal_text)
        self.seq = sequence[start_num-1:end_num]
        return self.seq

    # Sequence 붙이기
    def combine_seq(self, sequence, signal_text, chain_list):
        self.signal_peptide = self.sequence_slice(sequence, signal_text)

        for i in chain_list:
            full_seq = self.signal_peptide + i
            self.new_seq.append(full_seq)
        return self.new_seq



    # C 부분만 추출하기
    # C 부분 중 변수보다 높은 수 count

    # 만약 count 한 값이 마음에 들면 excel로 추출


filename = 'C:/Users/SD NOH/PycharmProjects/OpenInnovation/data/file1.xlsx'
# text = 'SIGNAL 1..18;  /evidence="ECO:0000250|UniProtKB:P11021"'
# seq_1 = 'MKFPMVAAALLLLCAVRAEEEDKKEDVGTVVGIDLGTTYSCVGVFKNGRVEIIANDQGNRITPSYVAFTPEGERLIGDAAKNQLTSNPENTVFDAKRLIGRTWNDPSVQQDIKFLPFKVVEKKTKPYIQVDIGGGQTKTFAPEEISAMVLTKMKETAEAYLGKKVTHAVVTVPAYFNDAQRQATKDAGTIAGLNVMRIINEPTAAAIAYGLDKREGEKNILVFDLGGGTFDVSLLTIDNGVFEVVATNGDTHLGGEDFDQRVMEHFIKLYKKKTGKDVRKDNRAVQKLRREVEKAKRALSSQHQARIEIESFFEGEDFSETLTRAKFEELNMDLFRSTMKPVQKVLEDSDLKKSDIDEIVLVGGSTRIPKIQQLVKEFFNGKEPSRGINPDEAVAYGAAVQAGVLSGDQDTGDLVLLDVCPLTLGIETVGGVMTKLIPRNTVVPTKKSQIFSTASDNQPTVTIKVYEGERPLTKDNHLLGTFDLTGIPPAPRGVPQIEVTFEIDVNGILRVTAEDKGTGNKNKITITNDQNRLTPEEIERMVNDAEKFAEEDKKLKERIDTRNELESYAYSLKNQIGDKEKLGGKLSSEDKETMEKAVEEKIEWLESHQDADIEDFKAKKKELEEIVQPIISKLYGSAGPPPTGEEDTSEKDEL'
# chain = [
#     'DIQMTQSPSSLSASVGDRVTITCRASQGIRNYLAWYQQKPGKAPKLLIYAASTLQSGVPSRFSGSGSGTDFTLTISSLQPEDVATYYCQRYNRAPYTFGQGTKVEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC',
#     'EVQLVESGGGLVQPGRSLRLSCAASGFTFDDYAMHWVRQAPGKGLEWVSAITWNSGHIDYADSVEGRFTISRDNAKNSLYLQMNSLRAEDTAVYYCAKVSYLSTASSLDYWGQGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK',
#     'QVQLVQSGVEVKKPGASVKVSCKASGYTFTNYYMYWVRQAPGQGLEWMGGINPSNGGTNFNEKFKNRVTLTTDSSTTTAYMELKSLQFDDTAVYYCARRDYRFDMGFDYWGQGTTVTVSSASTKGPSVFPLAPCSRSTSESTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTKTYTCNVDHKPSNTKVDKRVESKYGPPCPPCPAPEFLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSQEDPEVQFNWYVDGVEVHNAKTKPREEQFNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKGLPSSIEKTISKAKGQPREPQVYTLPPSQEEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSRLTVDKSRWQEGNVFSCSVMHEALHNHYTQKSLSLSLGK',
#     'EIVLTQSPATLSLSPGERATLSCRASKGVSTSGYSYLHWYQQKPGQAPRLLIYLASYLESGVPARFSGSGSGTDFTLTISSLEPEDFAVYYCQHSRDLPLTFGGGTKVEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC'
# ]

ec = excel_controller()
data_value, data_header = ec.call_excel(filename)

# sc = seq_controller()
# new_list = sc.combine_seq(seq_1, text, chain)